import type { Package } from "@/lib/packages";

export const corporatePackages: Package[] = [
  {
    id: "corporate-wayanad-retreat",
    name: "Corporate Wayanad Retreat",
    slug: "corporate-wayanad-retreat",
    destination: "Wayanad",
    destinationSlug: "wayanad",
    duration: "3 Days / 2 Nights",
    nights: 2,
    days: 3,
    price: 4500,
    priceLabel: "₹4,500",
    image: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&q=80",
    includes: ["Resort Stay", "Meals", "Conference Setup", "Team Activities"],
    highlights: ["Jungle Resort", "Bonfire", "Offsite Sessions", "Nature Trails"],
    description: "A compact offsite for teams that want productive sessions, fresh air, and low-friction logistics from Kerala.",
    badge: "Team Favorite",
  },
  {
    id: "corporate-goa-incentive",
    name: "Corporate Goa Incentive",
    slug: "corporate-goa-incentive",
    destination: "Goa",
    destinationSlug: "goa",
    duration: "4 Days / 3 Nights",
    nights: 3,
    days: 4,
    price: 8500,
    priceLabel: "₹8,500",
    image: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&q=80",
    includes: ["Beach Resort", "Breakfast & Dinner", "Airport Transfers", "Event Support"],
    highlights: ["Beach Party", "Cruise Evening", "Reward Trip", "Team Experiences"],
    description: "A high-energy incentive package combining reward travel, leisure time, and coordinated group hosting.",
    badge: "Incentive Pick",
  },
  {
    id: "corporate-kerala-backwaters",
    name: "Corporate Kerala Backwaters",
    slug: "corporate-kerala-backwaters",
    destination: "Alappuzha",
    destinationSlug: "alappuzha",
    duration: "4 Days / 3 Nights",
    nights: 3,
    days: 4,
    price: 15000,
    priceLabel: "₹15,000",
    image: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&q=80",
    includes: ["Premium Stay", "Houseboat Cruise", "Meals", "Meeting Space"],
    highlights: ["Backwater Cruise", "Leadership Retreat", "Kerala Cuisine", "Private Sessions"],
    description: "A slower, premium offsite with backwater cruising, quiet strategy time, and curated Kerala hospitality.",
    badge: "Executive",
  },
  {
    id: "corporate-thailand-team",
    name: "Corporate Thailand Team Tour",
    slug: "corporate-thailand-team-tour",
    destination: "Thailand",
    destinationSlug: "thailand",
    duration: "6 Days / 5 Nights",
    nights: 5,
    days: 6,
    price: 22000,
    priceLabel: "₹22,000",
    image: "https://images.unsplash.com/photo-1528181304800-259b08848526?w=800&q=80",
    includes: ["Flights", "Hotel Stay", "Breakfast", "Group Transfers"],
    highlights: ["Bangkok", "Krabi", "Island Day", "Team Celebration"],
    description: "An international team travel package designed for recognition trips, sales incentives, and annual getaways.",
    badge: "International",
  },
  {
    id: "corporate-ooty-conference",
    name: "Corporate Ooty Conference",
    slug: "corporate-ooty-conference",
    destination: "Ooty",
    destinationSlug: "ooty",
    duration: "3 Days / 2 Nights",
    nights: 2,
    days: 3,
    price: 6500,
    priceLabel: "₹6,500",
    image: "https://images.unsplash.com/photo-1583417319070-4a69db38a482?w=800&q=80",
    includes: ["Hotel Stay", "Breakfast & Dinner", "Meeting Hall", "Transfers"],
    highlights: ["Conference Setup", "Hill Station Stay", "Tea Estate Visit", "Team Dinner"],
    description: "A balanced conference package for teams that need structured meetings with a scenic hill-station backdrop.",
    badge: "Conference",
  },
];
