import type { Package } from "@/lib/packages";

export const pilgrimages: Package[] = [
  {
    id: "char-dham-yatra",
    name: "Char Dham Yatra",
    slug: "char-dham-yatra",
    destination: "Uttarakhand",
    destinationSlug: "uttarakhand",
    duration: "12 Days / 11 Nights",
    nights: 11,
    days: 12,
    price: 28000,
    priceLabel: "₹28,000",
    image: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800&q=80",
    includes: ["Flights from Hyderabad", "Hotel Stay", "All Meals", "Temple Transfers", "Guide Support"],
    highlights: ["Yamunotri", "Gangotri", "Kedarnath", "Badrinath"],
    description: "A complete Himalayan pilgrimage covering the four sacred dhams with coordinated stays and transfers from Andhra Pradesh.",
    badge: "Sacred Circuit",
  },
  {
    id: "vaishno-devi",
    name: "Vaishno Devi Darshan",
    slug: "vaishno-devi-darshan",
    destination: "Katra, Jammu",
    destinationSlug: "katra",
    duration: "5 Days / 4 Nights",
    nights: 4,
    days: 5,
    price: 14500,
    priceLabel: "₹14,500",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    includes: ["Flights from Hyderabad", "Hotel Stay", "Breakfast", "Darshan Assistance", "RFID Pass"],
    highlights: ["Katra Stay", "Mata Vaishno Devi", "Ardhkuwari", "Bhawan Visit"],
    description: "A focused Vaishno Devi journey with flight connectivity from Andhra Pradesh, smooth darshan planning, and comfortable access from Katra.",
    badge: "Popular",
  },
  {
    id: "tirupati-darshan",
    name: "Tirupati Balaji Darshan",
    slug: "tirupati-darshan",
    destination: "Tirupati, Andhra Pradesh",
    destinationSlug: "tirupati",
    duration: "2 Days / 1 Night",
    nights: 1,
    days: 2,
    price: 3800,
    priceLabel: "₹3,800",
    image: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=800&q=80",
    includes: ["AC Bus / Train", "Hotel Stay", "Breakfast", "SSD Darshan Pass", "Prasadam"],
    highlights: ["Tirumala Balaji Darshan", "SSD Priority Darshan", "Tonsuring Support", "Padmavathi Temple"],
    description: "Expertly managed Tirupati Balaji darshan from Vijayawada/Hyderabad — one of the most sacred temples in the world, just a short journey away.",
    badge: "Quick Darshan",
  },
  {
    id: "kashi-ayodhya-prayagraj",
    name: "Kashi Ayodhya Prayagraj",
    slug: "kashi-ayodhya-prayagraj",
    destination: "Uttar Pradesh",
    destinationSlug: "uttar-pradesh",
    duration: "7 Days / 6 Nights",
    nights: 6,
    days: 7,
    price: 16500,
    priceLabel: "₹16,500",
    image: "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=800&q=80",
    includes: ["Train/Flight from AP", "Hotel Stay", "Breakfast & Dinner", "Intercity Transfers", "Guide Support"],
    highlights: ["Kashi Vishwanath", "Ayodhya Ram Mandir", "Triveni Sangam", "Ganga Aarti"],
    description: "A North India pilgrimage through three deeply sacred cities — crafted for AP families and community groups with smooth transfers and full ritual support.",
    badge: "Best Seller",
  },
  {
    id: "sabarimala-package",
    name: "Sabarimala Package",
    slug: "sabarimala-package",
    destination: "Pathanamthitta, Kerala",
    destinationSlug: "sabarimala",
    duration: "3 Days / 2 Nights",
    nights: 2,
    days: 3,
    price: 5200,
    priceLabel: "₹5,200",
    image: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=800&q=80",
    includes: ["AC Bus from AP", "Basic Stay", "Breakfast", "Pilgrim Assistance"],
    highlights: ["Pampa", "Sannidhanam", "Temple Trek", "Group Coordination"],
    description: "An affordable Sabarimala pilgrimage package from Andhra Pradesh with comfortable travel, stay at Pamba, and expert group coordination.",
    badge: "Value Trip",
  },
];
