import type { Package } from "@/lib/packages";

export const pilgrimages: Package[] = [
  {
    id: "char-dham-yatra",
    name: "Char Dham Yatra",
    slug: "char-dham-yatra",
    destination: "Uttarakhand",
    destinationSlug: "uttarakhand",
    duration: "12 Days / 11 Nights",
    nights: 11,
    days: 12,
    price: 18000,
    priceLabel: "₹18,000",
    image: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800&q=80",
    includes: ["Hotel Stay", "Meals", "Temple Transfers", "Guide Support"],
    highlights: ["Yamunotri", "Gangotri", "Kedarnath", "Badrinath"],
    description: "A complete Himalayan pilgrimage covering the four sacred dhams with coordinated stays and transfers.",
    badge: "Sacred Circuit",
  },
  {
    id: "vaishno-devi",
    name: "Vaishno Devi Darshan",
    slug: "vaishno-devi-darshan",
    destination: "Katra",
    destinationSlug: "katra",
    duration: "4 Days / 3 Nights",
    nights: 3,
    days: 4,
    price: 9500,
    priceLabel: "₹9,500",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    includes: ["Hotel Stay", "Breakfast", "Pickup & Drop", "Darshan Assistance"],
    highlights: ["Katra Stay", "Mata Vaishno Devi", "Ardhkuwari", "Bhawan Visit"],
    description: "A focused Vaishno Devi journey designed for smooth darshan planning and comfortable access from Katra.",
    badge: "Popular",
  },
  {
    id: "tirupati-darshan",
    name: "Tirupati Darshan",
    slug: "tirupati-darshan",
    destination: "Tirupati",
    destinationSlug: "tirupati",
    duration: "3 Days / 2 Nights",
    nights: 2,
    days: 3,
    price: 6500,
    priceLabel: "₹6,500",
    image: "https://images.unsplash.com/photo-1518005020951-eccb494ad742?w=800&q=80",
    includes: ["Hotel Stay", "Breakfast", "Temple Transfers", "Darshan Support"],
    highlights: ["Tirumala", "Balaji Darshan", "Padmavathi Temple", "Local Sightseeing"],
    description: "A compact Tirupati package with temple logistics handled so the trip stays prayer-focused and efficient.",
    badge: "Quick Darshan",
  },
  {
    id: "kashi-ayodhya-prayagraj",
    name: "Kashi Ayodhya Prayagraj",
    slug: "kashi-ayodhya-prayagraj",
    destination: "Uttar Pradesh",
    destinationSlug: "uttar-pradesh",
    duration: "7 Days / 6 Nights",
    nights: 6,
    days: 7,
    price: 12000,
    priceLabel: "₹12,000",
    image: "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=800&q=80",
    includes: ["Hotel Stay", "Breakfast & Dinner", "Intercity Transfers", "Guide Support"],
    highlights: ["Kashi Vishwanath", "Ayodhya Ram Mandir", "Triveni Sangam", "Ganga Aarti"],
    description: "A North India pilgrimage through three spiritually significant cities with well-paced transfers and rituals.",
    badge: "Best Seller",
  },
  {
    id: "sabarimala-package",
    name: "Sabarimala Package",
    slug: "sabarimala-package",
    destination: "Sabarimala",
    destinationSlug: "sabarimala",
    duration: "3 Days / 2 Nights",
    nights: 2,
    days: 3,
    price: 3500,
    priceLabel: "₹3,500",
    image: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=800&q=80",
    includes: ["Basic Stay", "Transfers", "Breakfast", "Pilgrim Assistance"],
    highlights: ["Pampa", "Sannidhanam", "Temple Trek", "Group Coordination"],
    description: "An affordable Sabarimala pilgrimage package with practical stay, transport, and group travel coordination.",
    badge: "Value Trip",
  },
];
